policy_type: BCTransformerPromptPolicy
extra_num_layers: 0
extra_hidden_size: 128
embed_size: 64  # 64  384
key_size: 64  # 64  384
n_tasks: 10
R: 64

transformer_input_size: null
transformer_num_layers: 4
transformer_num_heads: 6  # 8(曾经调过8，但用的是6)
transformer_head_output_size: 64
transformer_mlp_hidden_size: 256  # 256 1536
transformer_dropout: 0.1
transformer_max_seq_len: 10

# prompt
prompt_param: [100, 2, 1e-1]  # e prompt pool size(M), e prompt length(l_p), ortho_mu

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: resnet_encoder.yaml
    - language_encoder: mlp_encoder.yaml
    - position_encoding@temporal_position_encoding: sinusoidal_position_encoding.yaml
    - policy_head: gmm_head.yaml
